# Generated by Django 6.0.2 on 2026-03-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_adress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='unpaid', max_length=100),
        ),
    ]
