# Generated by Django 6.0.2 on 2026-03-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_order_order_status_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_status',
        ),
    ]
